### PR TITLE
Limit idea post from proposal to the same segment as the proposal

### PR DESCRIPTION
**Pull request by ethanlee123**
ticket: https://trello.com/c/SVyz7ZGU
- submit idea and submit proposal (w/o going through propose idea btn) still shows multiple options as intended

Screenshot 2023-05-17 at 10 23 39 AM

### CODE REVIEW

**Comment by oscarlaaaa** [comment]
Mine seems to be showing N/A when I try to make an idea branching from a proposal with the segment of "Crd"; is this intended behaviour?

image

**Comment by ethanlee123** [comment]
> Mine seems to be showing N/A when I try to make an idea branching from a proposal with the segment of "Crd"; is this intended behaviour?
> 
> image

ooh im not sure if thats intended, lemme check on this

**Comment by ethanlee123** [comment]
@oscarlaaaa gonna have to sync up with you later to see how you got to that page.

i created a proposal with CRD -> clicked on the read more btn (via conversation).
But theres not button to even propose an idea

**Review by oscarlaaaa — APPROVED** [review]
looks good to me 8)

**Pull request merged**
